- name: Install npm
  become: true
  package:
    name: npm
    state: present
  when: client_dir.changed

- name: Install npm dependencies
  become: true
  shell: npm ci
  args:
    chdir: /opt/area/client
  when: client_dir.changed

- name: Build the client
  become: true
  shell: npm run build
  args:
    chdir: /opt/area/client
  register: client_dir
  when: client_dir.changed

- name: Move the build to the web server
  become: true
  become_user: area-client
  shell: cp dist/ {{ client_folder }}
  args:
    chdir: /opt/area/client
  when: client_dir.changed
