global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:{{ prometheus_port }}']

  - job_name: 'backend'
    static_configs:
      - targets: ['localhost:{{ backend_port }}/metrics']
