global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:{{ prometheus_port }}']

  - job_name: 'backend'
    metrics_path: '/api/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['{{ docker0_ip.stdout }}:{{ backend_port }}']
        labels:
          group: 'backend'
