- name: Install NGINX
  apt:
    name: nginx
    state: present
  become: true

- name: Stop NGINX Service
  service:
    name: nginx
    state: stopped
  become: true

- name: Disable NGINX Default Virtual Host
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  become: true

- name: Copy NGINX Configuration
  copy:
    src: "triggermenot.conf"
    dest: "/etc/nginx/conf.d/default.conf"
  become: true

- name: Install Certbot and NGINX Plugin
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
  become: true

- name: Obtain SSL Certificates
  command: certbot --nginx --non-interactive --agree-tos --email admin@triggermenot.net -d {{ item }}
  with_items:
    - triggermenot.net
    - app.triggermenot.net
    - backend.triggermenot.net
    - pgadmin.triggermenot.net
    - grafana.triggermenot.net
    - status.triggermenot.net
  become: true

- name: Set Up Auto Renewal for Let's Encrypt
  cron:
    name: "Renew Let's Encrypt Certificates"
    job: "certbot renew --quiet"
    state: present
    user: root
  become: true
