- name: Install NGINX
  apt:
    name: nginx
    state: present
  become: true

- name: Disable NGINX Default Virtual Host
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  become: true

- name: Copy NGINX Configuration
  copy:
    src: "triggermenot.conf"
    dest: "/etc/nginx/conf.d/default.conf"
  become: true

- name: Restart NGINX
  service:
    name: nginx
    state: restarted
  become: true
