- name: Base
  hosts: all
  roles:
    - base
  tags: base

- name: Nix
  hosts: all
  roles:
    - nix
  tags: nix

- name: Docker
  hosts: all
  roles:
    - docker
  tags: docker

- name: Postgres
  hosts: area
  roles:
    - postgres
  tags: postgres

- name: Backend
  hosts: area
  roles:
    - backend
  tags: backend

- name: client
  hosts: area
  roles:
    - client
  tags: client
